# Generated by Django 2.0.13 on 2019-03-26 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citekey', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=128)),
                ('species', models.CharField(max_length=128)),
                ('isi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='index of self-incompatibility')),
                ('breeding_system', models.CharField(blank=True, choices=[('SI', 'Self-incompatible'), ('SC', 'Self-compatible')], max_length=2, null=True)),
                ('pubref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traitref', to='traits.PubLocal')),
            ],
        ),
    ]
