# Generated by Django 2.0.13 on 2019-03-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='pubref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traitref', to='traits.Publocal'),
        ),
    ]
